-- Public profile table used by the Flask app.
-- auth.users stores the real auth account, while app_users lets the app
-- check duplicate emails and keep a simple user list for the project.
-- After running this file in Supabase SQL Editor, PostgREST is notified to
-- refresh its schema cache so new columns are visible to the REST API.
create table if not exists public.app_users (
    id uuid primary key,
    email text unique not null,
    full_name text,
    role text not null default 'user',
    phone_number text,
    delivery_address text,
    profile_image text,
    created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
    id bigint generated by default as identity primary key,
    name text not null,
    description text not null,
    category text not null,
    price numeric(10,2) not null,
    image text not null,
    is_available boolean not null default true,
    stock_quantity integer not null default 0,
    low_stock_threshold integer not null default 5,
    sizes jsonb -- For beverages: {"small": 20.0, "medium": 25.0, "large": 30.0}
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    customer_email text,
    order_number integer,
    table_number text,
    items jsonb not null,
    total_amount numeric(10,2) not null,
    payment_method text not null,
    payment_status text not null default 'Pending',
    payment_bank text,
    payment_reference text,
    payment_proof text,
    order_type text not null default 'Delivery',
    delivery_option text not null default 'Delivery',
    delivery_address text,
    preferred_time text,
    delivery_notes text,
    rider_id uuid,
    delivery_status text not null default 'Waiting',
    status text not null default 'Pending',
    inventory_deducted boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.riders (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    phone text,
    status text not null default 'Available'
);

create table if not exists public.employees (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    position text not null,
    contact_number text,
    shift_schedule text,
    attendance_status text not null default 'Off Duty',
    employment_status text not null default 'Active',
    notes text,
    task_assignment text,
    time_in text,
    time_out text,
    created_at timestamptz not null default now()
);

alter table public.orders add column if not exists payment_method text;
alter table public.orders add column if not exists customer_email text;
alter table public.orders add column if not exists payment_status text not null default 'Pending';
alter table public.orders add column if not exists payment_bank text;
alter table public.orders add column if not exists payment_reference text;
alter table public.orders add column if not exists payment_proof text;
alter table public.orders add column if not exists order_type text not null default 'Delivery';
alter table public.orders add column if not exists delivery_option text not null default 'Delivery';
alter table public.orders add column if not exists order_number integer;
alter table public.orders add column if not exists delivery_address text;
alter table public.orders add column if not exists preferred_time text;
alter table public.orders add column if not exists delivery_notes text;
alter table public.orders add column if not exists rider_id uuid;
alter table public.orders add column if not exists delivery_status text not null default 'Waiting';
alter table public.orders add column if not exists inventory_deducted boolean not null default false;
alter table public.app_users add column if not exists full_name text;
alter table public.app_users add column if not exists role text not null default 'user';
alter table public.app_users add column if not exists phone_number text;
alter table public.app_users add column if not exists delivery_address text;
alter table public.app_users add column if not exists profile_image text;
alter table public.menu_items add column if not exists is_available boolean not null default true;
alter table public.menu_items add column if not exists stock_quantity integer not null default 0;
alter table public.menu_items add column if not exists low_stock_threshold integer not null default 5;
alter table public.riders add column if not exists phone text;
alter table public.riders add column if not exists status text not null default 'Available';
alter table public.employees add column if not exists name text;
alter table public.employees add column if not exists position text;
alter table public.employees add column if not exists contact_number text;
alter table public.employees add column if not exists shift_schedule text;
alter table public.employees add column if not exists attendance_status text not null default 'Off Duty';
alter table public.employees add column if not exists employment_status text not null default 'Active';
alter table public.employees add column if not exists notes text;
alter table public.employees add column if not exists task_assignment text;
alter table public.employees add column if not exists time_in text;
alter table public.employees add column if not exists time_out text;
alter table public.employees add column if not exists created_at timestamptz not null default now();

do $$
begin
    if not exists (
        select 1
        from information_schema.table_constraints
        where table_schema = 'public'
          and table_name = 'orders'
          and constraint_name = 'orders_rider_id_fkey'
    ) then
        alter table public.orders
        add constraint orders_rider_id_fkey
        foreign key (rider_id) references public.riders(id)
        on delete set null;
    end if;
end $$;

-- Keep existing rows valid after adding these columns to an older database.
update public.orders
set payment_method = 'Cash'
where payment_method is null;

update public.orders
set payment_status = 'Pending'
where payment_status is null or btrim(payment_status) = '';

update public.orders
set order_type = 'Delivery'
where order_type is null or btrim(order_type) = '';

update public.orders
set delivery_option = case
    when order_type ilike 'pickup' then 'Pickup'
    else 'Delivery'
end
where delivery_option is null or btrim(delivery_option) = '';

update public.orders
set delivery_status = 'Waiting'
where delivery_status is null or btrim(delivery_status) = '';

update public.orders
set order_number = id::integer
where order_number is null;

create sequence if not exists public.orders_order_number_seq;

select setval(
    'public.orders_order_number_seq',
    greatest(coalesce((select max(order_number) from public.orders), 0), 0) + 1,
    false
);

alter table public.orders
alter column order_number set default nextval('public.orders_order_number_seq');

create unique index if not exists orders_order_number_unique
on public.orders(order_number)
where order_number is not null;

update public.app_users
set full_name = initcap(replace(split_part(email, '@', 1), '.', ' '))
where full_name is null or btrim(full_name) = '';

update public.app_users
set role = 'user'
where role is null or btrim(role) = '';

update public.menu_items
set is_available = true
where is_available is null;

update public.menu_items
set stock_quantity = 0
where stock_quantity is null or stock_quantity < 0;

update public.menu_items
set low_stock_threshold = 5
where low_stock_threshold is null or low_stock_threshold <= 0;

update public.menu_items
set is_available = false
where stock_quantity <= 0;

update public.riders
set status = 'Available'
where status is null or btrim(status) = '';

update public.employees
set attendance_status = 'Off Duty'
where attendance_status is null or btrim(attendance_status) = '';

update public.employees
set employment_status = 'Active'
where employment_status is null or btrim(employment_status) = '';

alter table public.app_users enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.riders enable row level security;
alter table public.employees enable row level security;

drop policy if exists "Allow app_users select" on public.app_users;
create policy "Allow app_users select"
on public.app_users for select
to anon
using (true);

drop policy if exists "Allow app_users insert" on public.app_users;
create policy "Allow app_users insert"
on public.app_users for insert
to anon
with check (true);

drop policy if exists "Allow app_users update" on public.app_users;
create policy "Allow app_users update"
on public.app_users for update
to anon
using (true)
with check (true);

drop policy if exists "Allow menu_items read" on public.menu_items;
create policy "Allow menu_items read"
on public.menu_items for select
to anon
using (true);

drop policy if exists "Allow orders read" on public.orders;
create policy "Allow orders read"
on public.orders for select
to anon
using (true);

drop policy if exists "Allow orders insert" on public.orders;
create policy "Allow orders insert"
on public.orders for insert
to anon
with check (true);

drop policy if exists "Allow orders update" on public.orders;
create policy "Allow orders update"
on public.orders for update
to anon
using (true)
with check (true);

drop policy if exists "Allow orders delete" on public.orders;
create policy "Allow orders delete"
on public.orders for delete
to anon
using (true);

drop policy if exists "Allow riders read" on public.riders;
create policy "Allow riders read"
on public.riders for select
to anon
using (true);

drop policy if exists "Allow riders insert" on public.riders;
create policy "Allow riders insert"
on public.riders for insert
to anon
with check (true);

drop policy if exists "Allow riders update" on public.riders;
create policy "Allow riders update"
on public.riders for update
to anon
using (true)
with check (true);

drop policy if exists "Allow riders delete" on public.riders;
create policy "Allow riders delete"
on public.riders for delete
to anon
using (true);

drop policy if exists "Allow employees read" on public.employees;
create policy "Allow employees read"
on public.employees for select
to anon
using (true);

drop policy if exists "Allow employees insert" on public.employees;
create policy "Allow employees insert"
on public.employees for insert
to anon
with check (true);

drop policy if exists "Allow employees update" on public.employees;
create policy "Allow employees update"
on public.employees for update
to anon
using (true)
with check (true);

drop policy if exists "Allow employees delete" on public.employees;
create policy "Allow employees delete"
on public.employees for delete
to anon
using (true);

insert into public.menu_items (name, description, category, price, image, is_available)
values
    ('Cheeseburger', 'Juicy beef burger with melted cheese and fresh vegetables.', 'Main Course', 60.00, 'cheeseburger.png', true),
    ('Chicken Burger', 'Crispy chicken burger served with a soft toasted bun.', 'Main Course', 60.00, 'chickenburger.png', true),
    ('Spicy Chicken', 'Flavorful chicken meal for customers who like some heat.', 'Main Course', 99.00, 'spicychicken.png', true),
    ('Beef Steak', 'Classic beef steak cooked with a rich savory taste.', 'Main Course', 99.00, 'beefsteak.png', true),
    ('Salmon Fillet', 'Tender salmon fillet with a clean and premium flavor.', 'Main Course', 99.00, 'salmonfillet.png', true),
    ('French Fries', 'Crispy golden fries served hot with a classic dip.', 'Appetizers', 40.00, 'french_fries.png', true),
    ('Spring Rolls', 'Crispy rolls filled with vegetables and savory meat.', 'Appetizers', 50.00, 'spring_rolls.png', true),
    ('Nachos', 'Tortilla chips topped with cheese and flavorful toppings.', 'Appetizers', 60.00, 'nachos.png', true),
    ('Calamares', 'Golden fried squid rings with a crunchy coating.', 'Appetizers', 70.00, 'calamares.png', true),
    ('Garlic Bread', 'Toasted bread brushed with garlic butter.', 'Appetizers', 45.00, 'garlic_bread.png', true),
    ('Coke', 'Refreshing carbonated cola drink.', 'Beverages', 25.00, 'coke.png', true),
    ('Iced Tea', 'Chilled tea with a bright lemon flavor.', 'Beverages', 20.00, 'ice_tea.png', true),
    ('Mango Juice', 'Fresh mango juice with a smooth tropical taste.', 'Beverages', 30.00, 'mango_juice.png', true),
    ('Lemonade', 'Sweet and tangy lemonade served cold.', 'Beverages', 25.00, 'lemonade.png', true),
    ('Water', 'Pure drinking water.', 'Beverages', 15.00, 'water.png', true)
on conflict do nothing;

create table if not exists public.otp_verifications (
    id bigserial primary key,
    email text not null,
    otp_hash text not null,
    purpose text not null check (purpose in ('registration', 'login')),
    expires_at timestamptz not null,
    attempts integer not null default 0,
    created_at timestamptz not null default now()
);

create index if not exists otp_verifications_email_purpose_created_idx
on public.otp_verifications (email, purpose, created_at desc);

alter table public.otp_verifications enable row level security;

drop policy if exists "Service role manages OTP verifications" on public.otp_verifications;
create policy "Service role manages OTP verifications"
on public.otp_verifications for all
to service_role
using (true)
with check (true);

-- Verify the columns exist in Postgres.
select table_name, column_name, data_type
from information_schema.columns
where table_schema = 'public'
  and (
      (table_name = 'orders' and column_name in ('customer_email', 'payment_method', 'payment_status', 'payment_bank', 'payment_reference', 'payment_proof', 'order_type', 'delivery_option', 'order_number', 'delivery_address', 'preferred_time', 'delivery_notes', 'rider_id', 'delivery_status', 'inventory_deducted'))
      or (table_name = 'app_users' and column_name in ('full_name', 'role', 'phone_number', 'delivery_address', 'profile_image'))
      or (table_name = 'riders' and column_name in ('name', 'phone', 'status'))
      or (table_name = 'menu_items' and column_name in ('is_available', 'stock_quantity', 'low_stock_threshold'))
      or (table_name = 'employees' and column_name in ('name', 'position', 'contact_number', 'shift_schedule', 'attendance_status', 'employment_status', 'notes', 'task_assignment', 'time_in', 'time_out'))
      or (table_name = 'otp_verifications' and column_name in ('id', 'email', 'otp_hash', 'purpose', 'expires_at', 'attempts', 'created_at'))
  )
order by table_name, column_name;

-- Refresh Supabase/PostgREST schema cache so REST requests stop seeing stale
-- "Could not find column in the schema cache" errors.
notify pgrst, 'reload schema';
select pg_notification_queue_usage();
