-- Public profile table used by the Flask app.
-- auth.users stores the real auth account, while app_users lets the app
-- check duplicate emails and keep a simple user list for the project.
-- After running this file in Supabase SQL Editor, PostgREST is notified to
-- refresh its schema cache so new columns are visible to the REST API.
create table if not exists public.app_users (
    id uuid primary key,
    email text unique not null,
    full_name text,
    created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
    id bigint generated by default as identity primary key,
    name text not null,
    description text not null,
    category text not null,
    price numeric(10,2) not null,
    image text not null,
    sizes jsonb -- For beverages: {"small": 20.0, "medium": 25.0, "large": 30.0}
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    table_number text,
    items jsonb not null,
    total_amount numeric(10,2) not null,
    payment_method text not null,
    status text not null default 'Pending',
    created_at timestamptz not null default now()
);

alter table public.orders add column if not exists payment_method text;
alter table public.app_users add column if not exists full_name text;

-- Keep existing rows valid after adding these columns to an older database.
update public.orders
set payment_method = 'Cash'
where payment_method is null;

update public.app_users
set full_name = initcap(replace(split_part(email, '@', 1), '.', ' '))
where full_name is null or btrim(full_name) = '';

alter table public.app_users enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Allow app_users select" on public.app_users;
create policy "Allow app_users select"
on public.app_users for select
to anon
using (true);

drop policy if exists "Allow app_users insert" on public.app_users;
create policy "Allow app_users insert"
on public.app_users for insert
to anon
with check (true);

drop policy if exists "Allow app_users update" on public.app_users;
create policy "Allow app_users update"
on public.app_users for update
to anon
using (true)
with check (true);

drop policy if exists "Allow menu_items read" on public.menu_items;
create policy "Allow menu_items read"
on public.menu_items for select
to anon
using (true);

drop policy if exists "Allow orders read" on public.orders;
create policy "Allow orders read"
on public.orders for select
to anon
using (true);

drop policy if exists "Allow orders insert" on public.orders;
create policy "Allow orders insert"
on public.orders for insert
to anon
with check (true);

drop policy if exists "Allow orders update" on public.orders;
create policy "Allow orders update"
on public.orders for update
to anon
using (true)
with check (true);

drop policy if exists "Allow orders delete" on public.orders;
create policy "Allow orders delete"
on public.orders for delete
to anon
using (true);

insert into public.menu_items (name, description, category, price, image)
values
    ('Cheeseburger', 'Juicy beef burger with melted cheese and fresh vegetables.', 'Main Course', 60.00, 'cheeseburger.png'),
    ('Cheese Sandwich', 'Toasted sandwich filled with cheese and a creamy spread.', 'Snack', 50.00, 'cheesesandwich.png'),
    ('Chicken Burger', 'Crispy chicken burger served with a soft toasted bun.', 'Main Course', 60.00, 'chickenburger.png'),
    ('Spicy Chicken', 'Flavorful chicken meal for customers who like some heat.', 'Main Course', 99.00, 'spicychicken.png'),
    ('Beef Steak', 'Classic beef steak cooked with a rich savory taste.', 'Main Course', 99.00, 'beefsteak.png'),
    ('Salmon Fillet', 'Tender salmon fillet with a clean and premium flavor.', 'Main Course', 99.00, 'salmonfillet.png')
on conflict do nothing;

-- Verify the columns exist in Postgres.
select table_name, column_name, data_type
from information_schema.columns
where table_schema = 'public'
  and (
      (table_name = 'orders' and column_name in ('payment_method'))
      or (table_name = 'app_users' and column_name in ('full_name'))
  )
order by table_name, column_name;

-- Refresh Supabase/PostgREST schema cache so REST requests stop seeing stale
-- "Could not find column in the schema cache" errors.
notify pgrst, 'reload schema';
select pg_notification_queue_usage();
